app:
  frontend-url: https://tradev.shop

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "https://tradev.shop/api/auth/oauth2/callback/google"

  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

  datasource:
    hikari:
      maximum-pool-size: 20

server:
  forward-headers-strategy: framework
  tomcat:
    threads:
      max: 200
  compression:
    enabled: true
    mime-types: application/json,text/html,text/plain

management:
  endpoint:
    health:
      show-details: never
  health:
    mail:
      enabled: false

logging:
  level:
    com.tradev: INFO
    root: WARN
  file:
    name: /app/logs/tradev.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
